# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gearman-Server
version:      1.10
version_from: lib/Gearman/Server.pm
installdirs:  site
requires:
    Danga::Socket:                 1.52
    Gearman::Util:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
