---
abstract: "function call \"router\" and load balancer"
author:
  - 'Brad Fitzpatrick (brad@danga.com), Brad Whitaker (whitaker@danga.com)'
build_requires:
  Test::More: 0
  Test::Script: 1.12
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman-Server
no_index:
  directory:
    - t
    - inc
requires:
  Danga::Socket: 1.52
  Gearman::Util: 0
  version: 0
version: v1.130.0
